# written by jxzou at 20200322
# updated by jxzou at 20200515: delete 'install', add $(BIN)
# updated by jxzou at 20221008: delete F2_MKL_FLAGS
# updated by ansatzX at 202310130: support brew_openblas

BIN = ../bin
LIB = ../mokit/lib

# --- gfortran + OpenBLAS ---
F90    = gfortran
CC = gcc    
FFLAGS = -O2 -cpp -fPIC
MKL_FLAGS = -L/opt/homebrew/opt/openblas/lib  -lopenblas
F2PY   = f2py
F2_FLAGS = --fcompiler=gnu
F2_F90_FLAGS = --f90flags="-cpp" 

include Makefile.main


